# Run `pre-commit autoupdate` to update to the latest pre-commit hooks version.
default_install_hook_types: [pre-commit, commit-msg]
repos:
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
    - id: codespell
  - repo: https://github.com/espressif/conventional-precommit-linter
    rev: v1.10.0
    hooks:
      - id: conventional-precommit-linter
        stages: [commit-msg]
  - repo: https://github.com/espressif/astyle_py.git
    rev: v1.1.0
    hooks:
      - id: astyle_py
        args: ['--astyle-version=3.4.7', '--rules=astyle-rules.yaml']
